### ISSUE TITLE
Crash after creeper explosion.

### ISSUE THREAD

**Issue by rokoblox** [CreativeMD/EnhancedVisuals#91]
Whenever a creeper explodes, the game crashes.
Minecraft 1.19
Fabric 0.14.7
EnhancedVisuals 1.5.5
Crashlog:
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/12/22, 10:21 PM
Description: Ticking entity

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1927 failed
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.1)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:418)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.server.world.ServerWorld.createExplosion(ServerWorld:1046)
	at net.minecraft.world.World.createExplosion(World:490)
	at net.minecraft.entity.mob.CreeperEntity.explode(CreeperEntity:245)
	at net.minecraft.entity.mob.CreeperEntity.tick(CreeperEntity:159)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:711)
	at net.minecraft.world.World.tickEntity(World:466)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:370)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:338)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:875)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:98)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:258)
	at java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413)
	... 19 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_1927::method_8348()V has incompatible changes at opcode 15 in callback enhancedvisuals.mixins.json:MixinExplosion from mod enhancedvisuals->@Inject::onDetonate(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/util/Set;IFIIIIIILjava/util/List;)V.
 Expected: [Ljava/util/Set;, I, F, I, I, I, I, I, I, Ljava/util/List;]
    Found: []
Available: []
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:547)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:418)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_3218.method_8454(class_3218.java:1046)
	at net.minecraft.class_1937.method_8437(class_1937.java:490)
	at net.minecraft.class_1548.method_7006(class_1548.java:245)
	at net.minecraft.class_1548.method_5773(class_1548.java:159)
	at net.minecraft.class_3218.method_18762(class_3218.java:711)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:370)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:338)

-- Entity being ticked --
Details:
	Entity Type: minecraft:creeper (net.minecraft.class_1548)
	Entity ID: 4582
	Entity Name: Creeper
	Entity's Exact location: -21.70, 55.00, -15.38
	Entity's Block location: World: (-22,55,-16), Section: (at 10,7,0 in -2,3,-1; chunk contains blocks -32,-64,-16 to -17,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Air:300s,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],ArmorItems:[{},{},{},{}],Attributes:[{Base:16.0d,Modifiers:[{Amount:-0.0027810906681405945d,Name:"Random spawn bonus",Operation:1,UUID:[I;1933468659,-762493876,-1905107122,1164595135]}],Name:"minecraft:generic.follow_range"},{Base:0.25d,Name:"minecraft:generic.movement_speed"}],BMLootBlock:0b,Brain:{memories:{}},CanPickUpLoot:0b,DeathTime:0s,ExplosionRadius:3b,FallDistance:0.0f,FallFlying:0b,Fire:-1s,Fuse:30s,HandDropChances:[0.085f,0.085f],HandItems:[{},{}],Health:10.444799f,HurtByTimestamp:46,HurtTime:0s,Invulnerable:0b,LeftHanded:1b,Motion:[0.0d,-0.0784000015258789d,0.004167565605926542d],OnGround:1b,PersistenceRequired:0b,PortalCooldown:0,Pos:[-21.69999998807907d,55.0d,-15.381429067245234d],Rotation:[226.46356f,0.0f],UUID:[I;272929045,1105870949,-1514401159,-932526539],ignited:0b}
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:370)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:338)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['rokoblox5'/4815, l='ServerWorld minecraft:overworld xbox world', x=-16.84, y=56.00, z=-19.32]]
	Chunk stats: 2809
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,65,0), Section: (at 0,1,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 37768 game time, 37768 day time
	Level name: xbox world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 75909 (now: false), thunder time: 44166 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1727725056 bytes (1647 MiB) / 5003804672 bytes (4772 MiB) up to 8455716864 bytes (8064 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) HD Graphics 530
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x191b
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8681
	Graphics card #1 name: NVIDIA Quadro M600M
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x13b2
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 16231.58
	Virtual memory used (MB): 11263.79
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8064m
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.0
		ambientsounds: Ambiend Sounds (Fabric) 5.2.0
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19
		appleskin: AppleSkin 2.4.0+mc1.19
			cloth-config: Cloth Config v6 7.0.65
				cloth-basic-math: cloth-basic-math 0.6.1
		architectury: Architectury 5.6.22
		bclib: BCLib 2.0.4
		betteranimalsplus: Better Animals Plus 1.19-11.0.6
		betterend: Better End 2.0.1
		betternether: Better Nether 7.0.1
		biomemakeover: Biome Makeover 1.19-beta-1.5.4
		bookshelf: Bookshelf 14.0.2
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.0-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		cardinal-components: Cardinal Components API 5.0.0-beta.1
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.0-beta.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			cardinal-components-item: Cardinal Components API (items) 5.0.0-beta.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.0-beta.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.0-beta.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.0-beta.1
		citresewn: CIT Resewn 1.1.0+1.19
			citresewn-defaults: CIT Resewn: Defaults 1.1.0+1.19
		continuity: Continuity 2.0.0+1.19
		creativecore: CreativeCore (Fabric) 2.6.14
		croptopia: Croptopia 2.0.5
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		dashloader: DashLoader 4.0.0+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		debugify: Debugify 2.0.0
			com_github_llamalad7_mixinextras: mixinextras 0.0.10
		deepslatecutting: Deepslate Cutting 1.4.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			maybe-data: Maybe data 1.3.1-1.18.2
		enchdesc: EnchantmentDescriptions 11.0.2
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.5
		entityculling: EntityCulling-Fabric 1.5.1-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		fabric: Fabric API 0.55.3+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.6+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.12+e62f51a3a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.5+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.1+cda9839ba9
			fabric-commands-v0: Fabric Commands (v0) 0.2.22+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.16+9ff28f40a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.0.1+2a5b9210a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.27+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.24+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.23+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.9+21a5acaaa9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.1+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.1+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.7+9ff28f40a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.5+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.16+92cf9a3ea9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.6+9ff28f40a9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+9e7660c6a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.23+9ff28f40a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.8+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.0+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.17.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.7
		fallingleaves: Falling Leaves 1.12.1+1.19
		fwaystones: Fabric Waystones 3.0.0
		geckolib3: Geckolib 3.1.2
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		immersive_portals: Immersive Portals 2.0.1
			imm_ptl_core: Immersive Portals Core 2.0.1
			q_misc_util: QMiscUtil 2.0.1
		indium: Indium 1.0.4+mc1.19
		infusion_table: Infusion Table 1.1.0
		jade: Jade 7.1.2
		jamlib: JamLib 0.0.8
		java: Java HotSpot(TM) 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lithium: Lithium 0.8.0
		midnightcontrols: MidnightControls 1.1.0+1.19
			midnightlib: MidnightLib 0.5.2
			org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		rightclickharvest: Right Click Harvest 2.0.8
		roughlyenoughitems: Roughly Enough Items 9.0.475
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19-1.0.6
		tooltipfix: ToolTip Fix 1.0.5-1.19
		visuality: Visuality 0.5.0
		xaeroworldmap: Xaero's World Map 1.23.2
		yosbr: YOSBR 0.1.1
	Server Running: true
	Player Count: 1 / 8; [class_3222['rokoblox5'/4815, l='ServerWorld minecraft:overworld xbox world', x=-16.84, y=56.00, z=-19.32]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.19
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 2
	Suspected Mods: None
```

**Comment by Arbiter549** [comment]
Same problem here, Heres my log
[crash-2022-06-12_17.01.04-client.txt](https://github.com/CreativeMD/EnhancedVisuals/files/8886856/crash-2022-06-12_17.01.04-client.txt)

**Comment by rokoblox** [comment]
I'm pretty sure the issue is [here].(https://github.com/CreativeMD/EnhancedVisuals/blob/1.19/src/main/java/team/creative/enhancedvisuals/mixin/MixinExplosion.java)
I'm not entirely sure because I'm not that experienced with mixin nor fabric modding but I think the method field has the name of the method but is missing its arguments, so I assume a fix would be to change the field on line 19 to `Lnet/minecraft/world/level/Explosion;explode(Ljava/util/Set;, I, F, I, I, I, I, I, I, Ljava/util/List;)V`

I tried manually fixing the issue by forking the project but I have gradle issues because dependencies are don't found and I have no idea how to load them lol.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
